#!/usr/bin/env bash
# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

if [ ! -e test-infra ]; then
  #### TEMP CHANGE: Since the changes that we want to test have not been
  ####              merged, we need to clone the test-infra scripts from
  ####              our own fork, rather than the upstream HEAD.
  #### git clone https://github.com/kubernetes/test-infra
  git clone -b testing_gce_dind https://github.com/leblancd/test-infra
fi

# Enable IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=0

./test-infra/jenkins/bootstrap.py \
    --job="${JOB_NAME}" \
    --service-account="${GOOGLE_APPLICATION_CREDENTIALS}" \
    "$@"
