#!/usr/bin/env bash
# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x

if [ ! -e test-infra ]; then
    git clone https://github.com/kubernetes/test-infra
fi

# Enable IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=0

export DOCKER_HOST=172.17.0.2:2375
export SKIP_SNAPSHOT=yes
export LOG=file
export IP_MODE=ipv4
export REMOTE_DNS64_V4SERVER=173.37.87.157

echo Running dind-cluster-v1.10.sh to bring up a cluster
/root/kubeadm-dind-cluster/fixed/dind-cluster-v1.10.sh up

# Delete the unused docker0 interface on kube-master, since the
# 172.17.0.0/16 subnet overlaps with the docker0 subnet on the host,
# causing 'kubectl' commands from this container to get bit-bucketed
# on kube-master.
docker exec kube-master ip link set docker0 down
docker exec kube-master brctl delbr docker0

# Start up a bash shell
exec bash

